# Generated by Django 3.2.11 on 2022-01-31 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('P', 'Phase'), ('T', 'Task'), ('U', 'User story'), ('B', 'Bug')], max_length=255)),
                ('status', models.CharField(choices=[('C', 'Closed'), ('D', 'Developed'), ('InP', 'In progress'), ('InT', 'In testing'), ('N', 'New'), ('R', 'Rejected'), ('S', 'Scheduled')], max_length=255)),
                ('assignee', models.CharField(max_length=255)),
                ('time_spent', models.DurationField(blank=True)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
