# Generated by Django 3.2.11 on 2022-02-01 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_auto_20220131_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='assignee',
        ),
        migrations.AddField(
            model_name='information',
            name='assignee',
            field=models.ManyToManyField(related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
