# Generated by Django 3.2.11 on 2022-02-01 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20220201_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='assignee',
        ),
        migrations.AddField(
            model_name='information',
            name='assignee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
