# Generated by Django 3.2.11 on 2022-02-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20220203_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='discussion',
            field=models.ManyToManyField(blank=True, to='tasks.Publication'),
        ),
    ]
